/*
 * Ruchina Perera, Manura Liyanawatte, Susith Sugathapala, Nadun Ferdinando
 * SLIIT
 * Batch 2
 * ST 2
 *
 */
package main;

import java.awt.*;
import javax.swing.*;

public class Home extends JFrame {

    Staff staffObj;


    public Home() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);        
        Container c = getContentPane();
        c.removeAll();
        c.setBounds(0,0,getContentPane().getWidth(),getContentPane().getHeight());
        c.setVisible(true);
        homePanel1.setSize(getContentPane().getWidth(),getContentPane().getHeight());
        c.add(homePanel1);  
    }
    public Home(Staff stObj) {
        this.staffObj = stObj;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        Container c = getContentPane();
        c.removeAll();
        c.setBounds(0,0,getContentPane().getWidth(),getContentPane().getHeight());
        c.setVisible(true);
        homePanel1.setSize(getContentPane().getWidth(),getContentPane().getHeight());
        c.add(homePanel1);  
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        test1 = new main.Test();
        homePanel1 = new main.HomePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnHome = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAddFlight = new javax.swing.JMenuItem();
        mnViewFlight = new javax.swing.JMenuItem();
        mnFlightReports = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAddPassenger = new javax.swing.JMenuItem();
        mnViewPassenger = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnAddTicket = new javax.swing.JMenuItem();
        mnViewTicket = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnAddStaff = new javax.swing.JMenuItem();
        mnViewStaff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AirLine Ticket Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 2147483647));
        setName("frameMain"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new java.awt.GridLayout());
        getContentPane().add(test1);
        getContentPane().add(homePanel1);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenu1.setText("File");

        mnHome.setText("Home");
        mnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHomeActionPerformed(evt);
            }
        });
        jMenu1.add(mnHome);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Flights");

        mnAddFlight.setText("Add Flight");
        mnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddFlightActionPerformed(evt);
            }
        });
        jMenu2.add(mnAddFlight);

        mnViewFlight.setText("View Flight");
        jMenu2.add(mnViewFlight);

        mnFlightReports.setText("Flight Reports");
        jMenu2.add(mnFlightReports);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Passengers");

        mnAddPassenger.setText("Add Passenger");
        mnAddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddPassengerActionPerformed(evt);
            }
        });
        jMenu3.add(mnAddPassenger);

        mnViewPassenger.setText("View Passengers");
        jMenu3.add(mnViewPassenger);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tickets");

        mnAddTicket.setText("Add Ticket");
        jMenu4.add(mnAddTicket);

        mnViewTicket.setText("View Ticket");
        jMenu4.add(mnViewTicket);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Staff");

        mnAddStaff.setText("Add Staff");
        jMenu5.add(mnAddStaff);

        mnViewStaff.setText("View Staff");
        jMenu5.add(mnViewStaff);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("homeFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        Login lgObj = new Login();
        this.setVisible(false);
        this.dispose();
        lgObj.setVisible(true);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddFlightActionPerformed
        Container c = getContentPane();
        c.removeAll();
        c.revalidate();
        c.repaint();
        c.setBounds(0,0,getContentPane().getWidth(),getContentPane().getHeight());
        test1.setSize(getContentPane().getWidth(),getContentPane().getHeight());
        c.setVisible(true);
        c.add(test1);       
    }//GEN-LAST:event_mnAddFlightActionPerformed

    private void mnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHomeActionPerformed
        Container c = getContentPane();
        c.removeAll();
        c.revalidate();
        c.repaint();
        c.setBounds(0,0,getContentPane().getWidth(),getContentPane().getHeight());
        homePanel1.setSize(getContentPane().getWidth(),getContentPane().getHeight());
        c.setVisible(true);
        c.add(homePanel1);   
    }//GEN-LAST:event_mnHomeActionPerformed

    private void mnAddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddPassengerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnAddPassengerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.HomePanel homePanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAddFlight;
    private javax.swing.JMenuItem mnAddPassenger;
    private javax.swing.JMenuItem mnAddStaff;
    private javax.swing.JMenuItem mnAddTicket;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnFlightReports;
    private javax.swing.JMenuItem mnHome;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnViewFlight;
    private javax.swing.JMenuItem mnViewPassenger;
    private javax.swing.JMenuItem mnViewStaff;
    private javax.swing.JMenuItem mnViewTicket;
    private main.Test test1;
    // End of variables declaration//GEN-END:variables
}
